In [1]:
import numpy as np
import pandas as pd

In [16]:
data=pd.read_csv("kc_house_data.csv")

In [17]:
data.shape

(21613, 21)

In [18]:
data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [19]:
data.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [20]:
data1=data.drop(labels="id",axis=1)

In [21]:
data1.head()

date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  20141013T000000  221900.0         3       1.00         1180      5650   
1  20141209T000000  538000.0         3       2.25         2570      7242   
2  20150225T000000  180000.0         2       1.00          770     10000   
3  20141209T000000  604000.0         4       3.00         1960      5000   
4  20150218T000000  510000.0         3       2.00         1680      8080   

   floors  waterfront  view  condition  grade  sqft_above  sqft_basement  \
0     1.0           0     0          3      7        1180              0   
1     2.0           0     0          3      7        2170            400   
2     1.0           0     0          3      6         770              0   
3     1.0           0     0          5      7        1050            910   
4     1.0           0     0          3      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503

In [22]:
# i dont think longitude ,latitude , year_built is imp
data1=data1.drop(["lat","date","long"],1)

In [23]:
data1.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode  sqft_living15  sqft_lot15  
0    98178           1340        5650  
1    98125           1690        7639  
2    98028           2720        8062  
3    98136           1360        5000  
4    98074           1800        7503

In [24]:
data1.zipcode.unique()

array([98178, 98125, 98028, 98136, 98074, 98053, 98003, 98198, 98146,
       98038, 98007, 98115, 98107, 98126, 98019, 98103, 98002, 98133,
       98040, 98092, 98030, 98119, 98112, 98052, 98027, 98117, 98058,
       98001, 98056, 98166, 98023, 98070, 98148, 98105, 98042, 98008,
       98059, 98122, 98144, 98004, 98005, 98034, 98075, 98116, 98010,
       98118, 98199, 98032, 98045, 98102, 98077, 98108, 98168, 98177,
       98065, 98029, 98006, 98109, 98022, 98033, 98155, 98024, 98011,
       98031, 98106, 98072, 98188, 98014, 98055, 98039], dtype=int64)

In [26]:
data1.waterfront.unique()

array([0, 1], dtype=int64)

In [27]:
data1.view.unique()

array([0, 3, 4, 2, 1], dtype=int64)

In [28]:
data1.sqft_basement.unique()

array([   0,  400,  910, 1530,  730, 1700,  300,  970,  760,  720,  700,
        820,  780,  790,  330, 1620,  360,  588, 1510,  410,  990,  600,
        560,  550, 1000, 1600,  500, 1040,  880, 1010,  240,  265,  290,
        800,  540,  380,  710,  840,  770,  480,  570, 1490,  620, 1250,
       1270,  120,  650,  180, 1130,  450, 1640, 1460, 1020, 1030,  750,
        640, 1070,  490, 1310,  630, 2000,  390,  430,  850,  210, 1430,
       1950,  440,  220, 1160,  860,  580, 2060, 1820, 1180,  200, 1150,
       1200,  680,  530, 1450, 1170, 1080,  960, 1100,  280,  870,  460,
       1400, 1320,  660, 1220,  900,  420, 1580, 1380,  475,  690,  270,
        350,  935, 1370,  980, 1470,  160,  950,   50,  740, 1780, 1900,
        340,  470,  370,  140, 1760,  130,  610,  520,  890, 1110,  150,
       1720,  810,  190, 1290,  670, 1800, 1120, 1810,   60, 1050,  940,
        310,  930, 1390, 1830, 1300,  510, 1330, 1590,  920, 1420, 1240,
       1960, 1560, 2020, 1190, 2110, 1280,  250, 23

In [29]:
data1.yr_renovated.unique()

array([   0, 1991, 2002, 2010, 1999, 1992, 2013, 1994, 1978, 2005, 2008,
       2003, 1984, 1954, 2014, 2011, 1974, 1983, 1945, 1990, 1988, 1957,
       1977, 1981, 1995, 2000, 1998, 1970, 1989, 2004, 1986, 2009, 2007,
       1987, 1973, 2006, 1985, 2001, 1980, 1971, 1979, 1997, 1950, 1969,
       1948, 2015, 1968, 2012, 1963, 1951, 1993, 1962, 1996, 1972, 1953,
       1955, 1982, 1956, 1940, 1976, 1946, 1975, 1958, 1964, 1959, 1960,
       1967, 1965, 1934, 1944], dtype=int64)

In [25]:
data1.dtypes

price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [30]:
data1.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode  sqft_living15  sqft_lot15  
0    98178           1340        5650  
1    98125           1690        7639  
2    98028           2720        8062  
3    98136           1360        5000  
4    98074           1800        7503

In [ ]:
#adding dummies

In [31]:
cont = pd.get_dummies(data1['bedrooms'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="bedrooms",axis=1)

In [32]:
data1.bathrooms.unique()

array([1.  , 2.25, 3.  , 2.  , 4.5 , 1.5 , 2.5 , 1.75, 2.75, 3.25, 4.  ,
       3.5 , 0.75, 4.75, 5.  , 4.25, 3.75, 0.  , 1.25, 5.25, 6.  , 0.5 ,
       5.5 , 6.75, 5.75, 8.  , 7.5 , 7.75, 6.25, 6.5 ])

In [33]:
data1["bathrooms"]=data1.bathrooms.apply(lambda x: round(x))

In [34]:
data1.bathrooms.unique()

array([1, 2, 3, 4, 5, 0, 6, 7, 8], dtype=int64)

In [35]:
cont = pd.get_dummies(data1['bathrooms'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="bathrooms",axis=1)

In [36]:
data1.floors.unique()

array([1. , 2. , 1.5, 3. , 2.5, 3.5])

In [37]:
data1["floors"]=data1.floors.apply(lambda x: round(x))

In [38]:
cont = pd.get_dummies(data1['floors'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="floors",axis=1)

In [39]:
cont = pd.get_dummies(data1['view'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="view",axis=1)

In [40]:
data1.condition.unique()

array([3, 5, 4, 1, 2], dtype=int64)

In [41]:
cont = pd.get_dummies(data1['condition'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="condition",axis=1)

In [42]:
data1.grade.unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1], dtype=int64)

In [43]:
cont = pd.get_dummies(data1['grade'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="grade",axis=1)

In [44]:
data1.sqft_basement.unique()

array([   0,  400,  910, 1530,  730, 1700,  300,  970,  760,  720,  700,
        820,  780,  790,  330, 1620,  360,  588, 1510,  410,  990,  600,
        560,  550, 1000, 1600,  500, 1040,  880, 1010,  240,  265,  290,
        800,  540,  380,  710,  840,  770,  480,  570, 1490,  620, 1250,
       1270,  120,  650,  180, 1130,  450, 1640, 1460, 1020, 1030,  750,
        640, 1070,  490, 1310,  630, 2000,  390,  430,  850,  210, 1430,
       1950,  440,  220, 1160,  860,  580, 2060, 1820, 1180,  200, 1150,
       1200,  680,  530, 1450, 1170, 1080,  960, 1100,  280,  870,  460,
       1400, 1320,  660, 1220,  900,  420, 1580, 1380,  475,  690,  270,
        350,  935, 1370,  980, 1470,  160,  950,   50,  740, 1780, 1900,
        340,  470,  370,  140, 1760,  130,  610,  520,  890, 1110,  150,
       1720,  810,  190, 1290,  670, 1800, 1120, 1810,   60, 1050,  940,
        310,  930, 1390, 1830, 1300,  510, 1330, 1590,  920, 1420, 1240,
       1960, 1560, 2020, 1190, 2110, 1280,  250, 23

In [45]:
def fun(x):
    if x==0:
        return 0
    elif x>0 & x<500:
        return 1
    elif x>500 & x<1000:
        return 2
    elif x>1000 & x<2000:
        return 3
    else:
        return 4

In [46]:
data1["sqft_basement"]=data1.sqft_basement.apply(lambda x: fun(x))

In [47]:
cont = pd.get_dummies(data1['sqft_basement'],prefix='no.',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="sqft_basement",axis=1)

In [49]:
data1["yr_renovated"]=data1.yr_renovated.map(lambda x: 1 if x>0 else x)

In [50]:
cont = pd.get_dummies(data1['zipcode'],prefix='zip',drop_first=True)
#Adding the results to the master dataframe
data1 = pd.concat([data1,cont],axis=1)
data1=data1.drop(labels="zipcode",axis=1)

In [51]:
data1.head()

price  sqft_living  sqft_lot  waterfront  sqft_above  yr_built  \
0  221900.0         1180      5650           0        1180      1955   
1  538000.0         2570      7242           0        2170      1951   
2  180000.0          770     10000           0         770      1933   
3  604000.0         1960      5000           0        1050      1965   
4  510000.0         1680      8080           0        1680      1987   

   yr_renovated  sqft_living15  sqft_lot15  no._1    ...      zip_98146  \
0             0           1340        5650      0    ...              0   
1             1           1690        7639      0    ...              0   
2             0           2720        8062      0    ...              0   
3             0           1360        5000      0    ...              0   
4             0           1800        7503      0    ...              0   

   zip_98148  zip_98155  zip_98166  zip_98168  zip_98177  zip_98178  \
0          0          0          0          0          0          1   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   zip_98188  zip_98198  zip_98199  
0          0          0          0  
1          0          0          0  
2          0          0          0  
3          0          0          0  
4          0          0          0  

[5 rows x 121 columns]

In [52]:
X=data1.drop(labels="price",axis=1)
y=data1["price"]

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [64]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Linear Regression
reg = LinearRegression()
regmodel = reg.fit(X_train, y_train)

coef = reg.coef_

y_predtrain = regmodel.predict(X_train)

y_predtest = regmodel.predict(X_test)

In [66]:
RMSEtrain = mean_squared_error(y_train, y_predtrain)**0.5
RMSEtest = mean_squared_error(y_test, y_predtest)**0.5
r2_train = r2_score(y_train, y_predtrain)
r2_test = r2_score(y_test, y_predtest)
print("RMSE for the training data is: ", RMSEtrain)
print("RMSE for the testing data is: ", RMSEtest)
print("R^2 value for training data is: ", r2_train)
print("R^2 value for testing data is: ", r2_test)


RMSE for the training data is:  149868.71162711398
RMSE for the testing data is:  137765.63423039863
R^2 value for training data is:  0.8382712952986047
R^2 value for testing data is:  0.8406232256197717
